use phf::phf_map;

// TOP 500+ najčešćih hrvatskih riječi bez dijakritika.
// Vraćeno iz originalne cro_stem implementacije kako bi se osigurala točnost.

static DIACRITIC_MAP: phf::Map<&'static str, &'static str> = phf_map! {
    "brze" => "brže",
    "brzeg" => "bržeg",
    "brzi" => "brži",
    "c" => "č",
    "citati" => "čitati",
    "covjek" => "čovjek",
    "covjeka" => "čovjeka",
    "covjeku" => "čovjeku",
    "d" => "đ",
    "djecaci" => "dječaci",
    "djecacima" => "dječacima",
    "djecaka" => "dječaka",
    "djevojcica" => "djevojčica",
    "drazi" => "draži",
    "duzeg" => "dužeg",
    "duzi" => "duži",
    "govoreci" => "govoreći",
    "gradjevinski" => "građevinski",
    "jucer" => "jučer",
    "kceri" => "kćeri",
    "kisobran" => "kišobran",
    "kuca" => "kuća",
    "kucama" => "kućama",
    "laksi" => "lakši",
    "macka" => "mačka",
    "najbrze" => "najbrže",
    "najbrzi" => "najbrži",
    "najljepsi" => "najljepši",
    "orascici" => "oraščići",
    "pecen" => "pečen",
    "peces" => "pečeš",
    "peci" => "peći",
    "pjevajuci" => "pjevajući",
    "pjevas" => "pjevaš",
    "pticica" => "ptičica",
    "rece" => "reče",
    "rekavsi" => "rekavši",
    "rekose" => "rekoše",
    "s" => "š",
    "skacem" => "skačem",
    "skacu" => "skaču",
    "skocivsi" => "skočivši",
    "srednjoskolka" => "srednjoškolka",
    "strozi" => "stroži",
    "strucnjaci" => "stručnjaci",
    "suma" => "šuma",
    "tezi" => "teži",
    "trcanje" => "trčanje",
    "ucenici" => "učenici",
    "vidjevsi" => "vidjevši",
    "vodicima" => "vodičima",
    "vucem" => "vučem",
    "z" => "ž",
};


// Mapa za preslikavanje ekavskih/ikavskih varijanti u ijekavicu.
static DIALECT_MAP: phf::Map<&'static str, &'static str> = phf_map! {
    "lepo" => "lijepo",
    "lepa" => "lijepa",
    "lepi" => "lijepi",
    "lep" => "lijep",
    "mleko" => "mlijeko",
    "mesec" => "mjesec",
    "beo" => "bijel",
    "belo" => "bijelo",
    "bela" => "bijela",
    "beli" => "bijeli",
    "pesma" => "pjesma",
    "dete" => "dijete",
    "covek" => "čovjek",
    "devojka" => "djevojka",
    "sneg" => "snijeg",
    "vreme" => "vrijeme",
    "breg" => "brijeg",
    "svet" => "svijet",
    "svetski" => "svjetski",
    "reka" => "rijeka",
    "reč" => "riječ",
    "gde" => "gdje",
    "ovde" => "ovdje",
    "onde" => "ondje",
    "nigde" => "nigdje",
    "svugde" => "svugdje",
    "deca" => "djeca",
    "decak" => "dječak",
    "sesti" => "sjesti",
    "cediti" => "cijediti",
    "zeleti" => "željeti",
    "goreti" => "gorjeti",
    "videti" => "vidjeti",
    "leteti" => "letjeti",
    "živeti" => "živjeti",
    "hteti" => "htjeti",
    "smeti" => "smjeti",
    "voleti" => "voljeti",
    "dite" => "dijete",
    "lik" => "lijek",
    "lip" => "lijep",
    "lipa" => "lijepa",
    "lipo" => "lijepo",
    "mliko" => "mlijeko",
    "snig" => "snijeg",
    "svit" => "svijet",
    "vridan" => "vrijedan",
    "vridnost" => "vrijednost",
    "cviće" => "cvijeće",
    "cvi" => "cvijet",
    "misto" => "mjesto",
    "siditi" => "sjediti",
    "viditi" => "vidjeti",
    "tilo" => "tijelo",
    "cilo" => "cijelo",
    "pivati" => "pjevati",
    "divojka" => "djevojka",
    "did" => "djed",
    "ljep" => "lijep",
};

pub fn get_diacritic_mapping(word: &str) -> Option<&'static str> {
    DIACRITIC_MAP.get(word).copied().or_else(|| DIALECT_MAP.get(word).copied())
}
